// The innerHTML is used to add the content between the tag
// document.getElementById("value").innerHTML = "This is Paragraph";

// document write is used to add the content directly on webpage
// document.write("This paragraph is generated by document dot write");

// To show the message as a popup
// alert("This is alert");

// To show output in console
// console.log("This output will be shown in console");
